services:
  database:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jokesdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  joke-service:
    build: ./joke-service
    container_name: joke-service
    ports:
      - "3000:3000"
    depends_on:
      - database

  submit-service:
    build: ./submit-service
    container_name: submit-service
    ports:
      - "3001:3001"
    depends_on:
      - database
      - joke-service
      - rabbitmq
    volumes:
      - submit-cache:/app/cache

  etl-service:
    build: ./etl-service
    container_name: etl-service
    depends_on:
      - rabbitmq
      - database

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mysql-data:
  rabbitmq-data:
  submit-cache: